### ISSUE TITLE
How can I use  gevet witth brod on kafka 0.7.2?

### ISSUE THREAD

**Issue by davidmontgom** [DataDog/brod#29]
How can I use  gevet witth brod on kafka 0.7.2?No handlers could be found for logger "brod.socket"
Traceback (most recent call last):
  File "/var/chef/cache/src/gevent/gevent/greenlet.py", line 328, in run
    result = self._run(_self.args, *_self.kwargs)
  File "worker_server.py", line 204, in execute_kafka_pipe
    kafka.produce(topic,payload)
  File "/usr/local/lib/python2.7/dist-packages/brod-0.3.2-py2.7.egg/brod/base.py", line 287, in produce
    return self._write(request, callback)
  File "/usr/local/lib/python2.7/dist-packages/brod-0.3.2-py2.7.egg/brod/blocking.py", line 98, in _write
    return self._write(data, callback, retries)
  File "/usr/local/lib/python2.7/dist-packages/brod-0.3.2-py2.7.egg/brod/blocking.py", line 89, in _write
    wrote_length += self._socket.send(data)
  File "/var/chef/cache/src/gevent/gevent/socket.py", line 441, in send
    self._wait(self._write_event)
  File "/var/chef/cache/src/gevent/gevent/socket.py", line 292, in _wait
    assert watcher.callback is None, 'This socket is already used by another greenlet: %r' % (watcher.callback, )
AssertionError: This socket is already used by another greenlet: <bound method Waiter.switch of <gevent.hub.Waiter object at 0x1dece60>>
<Greenlet at 0x1d4b9b0: execute_kafka_pipe('topic-spend', '{"enode": 1, "city": "Cairns", "dl": "en", "wnode)> failed with AssertionError

**Comment by technovangelist** [comment]
hi @davidmontgom - Thanks for your interest. This repo is no longer maintained and will be removed in 3 months (on or soon after June 30, 2015). If you are still interested in the functionality offered, we suggest looking at https://github.com/mumrah/kafka-python which is being actively maintained.
